### PR TITLE
Social media links

### PR DESCRIPTION
**Pull request by bricehalder**
Adds Discord and Github links to footer
Screen Shot 2022-02-09 at 2 09 10 PM

### CODE REVIEW

**Comment by dqian3** [comment]
Let's hold off on this til release?

**Comment by bricehalder** [comment]
Updated with beta disclaimer and link to about page.

https://user-images.githubusercontent.com/17424008/155298393-1bb33b7d-9aef-4176-b3e2-60265e8de93c.mov

**Comment by bricehalder** [comment]
I can also put the disclaimer on the home page instead of/in addition to the about page, just lmk

**Comment by dqian3** [comment]
I think this is fine

**Review by dqian3 — APPROVED** [review]

**Pull request merged**
