### PR TITLE
sprint and marathon mobile UI changes

### PR DESCRIPTION
**Pull request by mliu59**

### CODE REVIEW

**Comment by mliu59** [comment]
Sprint timebox collapsed and expanded: 
image
image

**Comment by mliu59** [comment]
Desktop sprint timebox collapsed and expanded
image
image

**Comment by mliu59** [comment]
mobile marathon timebox collapsed and expanded
image
image

**Comment by mliu59** [comment]
desktop marathon timebox collapsed and expanded
image
image

**Comment by mliu59** [comment]
For mobile, the "winning page" for marathon temporarily replaces the timebox contents, but still collapsible 
image
image

**Comment by mliu59** [comment]
For desktop, the "winning notif" is shown as a popup: 
image

**Comment by bricehalder** [comment]
This is really sweet!! For the winning text on mobile, would it be tough to disable the collapse for that screen only? I think that part doesn't make sense for it to be collapsible.

**Comment by mliu59** [comment]
> This is really sweet!! For the winning text on mobile, would it be tough to disable the collapse for that screen only? I think that part doesn't make sense for it to be collapsible.

Yeah agreed, will make that change

**Comment by dqian3** [comment]
I think rather than translating, we should have a specific "collapsed UI"

**Comment by mliu59** [comment]
build errors coming from checks for streaks. WIll be addressed in a different PR

**Comment by mliu59** [comment]
image
image
image
image

**Comment by mliu59** [comment]
image
image
image
image
image
image

**Comment by mliu59** [comment]
switched to a separate "collpased UI" instead of translating timebox

**Comment by dqian3** [comment]
this might be a pain with how I implmented the tutorial boxes, we should refactor it before merging either one of these in

**Review by dqian3 — CHANGES_REQUESTED** [review]
You probably need to take another look at this cause of the tutorial changes to the css styling

**Comment by maggarwal99** [comment]
@mliu59 if you're gonna refactor this and if it's not too much hassle then you might want to take a look at Bootstrap's [accordion](https://getbootstrap.com/docs/5.1/components/accordion/) and [collapse](https://getbootstrap.com/docs/5.1/components/collapse/) components.

**Comment by dqian3** [comment]
> @mliu59 if you're gonna refactor this and if it's not too much hassle then you might want to take a look at Bootstrap's [accordion](https://getbootstrap.com/docs/5.1/components/accordion/) and [collapse](https://getbootstrap.com/docs/5.1/components/collapse/) components.

Yeah, those definitely would make sense here

**Comment by mliu59** [comment]
@dqian3 @maggarwal99 Resolved conflicts with the tutorial changes to HUD. Added the timebox wrappers, etc.

Open to feedback, but I opted against using bootstrap's collapse and accordion for the same reasons why we didn't keep the translating timebox: mostly because the elements we want to show while the timebox is collapsed vs. expanded isn't necessarily consistent with each other (things like row and col order, font size, etc.). So we would need to basically create a separate collapsed vs expanded UI anyway. See image for example
image

**Review by dqian3 — APPROVED** [review]
LGTM

**Review by maggarwal99 — APPROVED** [review]
Makes sense, the rest lgtm

**Pull request merged**
