### PR TITLE
sprint mobile UI fixes

### PR DESCRIPTION
**Pull request by mliu59**
First round of fixes for the mobile UI:

- Reduced article and timebox font size
- reduced margins/padding to make the timebox much more compact on mobile
- removed display page preview on "hover" (I couldn't think of a way for mobile users to also get page previews in the article itself), 
- Kept the end article preview icon (now a click toggle instead of on hover)

### CODE REVIEW

**Comment by mliu59** [comment]
image
On tapping on icon:
image

**Comment by mliu59** [comment]
Also added 'more citation needed' box to the list of elements to remove (#261 )

**Review by maggarwal99 — APPROVED** [review]
We should consider using responsive web dev patterns to make the game platform-agnostic / more mobile friendly in the future https://developers.google.com/web/fundamentals/design-and-ux/responsive/patterns

**Comment by dqian3** [comment]
Hmm, I think for mobile the hud could take the whole width of the screen, the space on the side doesn't do much

**Comment by bricehalder** [comment]
Perhaps the HUD could just be hidden most of the time? and maybe just tucked into the side somewhere. And if someone taps the thing it will slide out

**Comment by mliu59** [comment]
Implemented @dqian3 's suggestion. opened a new issue for @bricehalder 's suggestion. I think that's a great idea, but seems like a larger effort

**Comment by mliu59** [comment]
image

**Pull request merged**
