### PR TITLE
Added arrows to path

### LINKED ISSUE #529: Make marathon checkpoints look better
Screenshot 2023-11-21 at 4 43 40 AM

Maybe replace the commas with arrows or emojis and remove the quotes and brackets

### PR DESCRIPTION
**Pull request by imvbh**
Change:
Removed the list type output[ quotes(") and commas(,)] on the results page and added arrow→ to represent a flow.
This fixes #529

### CODE REVIEW

**Comment by imvbh** [comment]
@bricehalder could you review this one please?

**Comment by mliu59** [comment]
@imvbh Thanks for putting in this PR! I'm wondering if there's a different symbol we can use instead of arrows to delimit the starting checkpoints. Users can go to any checkpoint in any order, so we don't want to give them the idea that they can only go in a specific order.

**Comment by imvbh** [comment]
@mliu59 I don't think I am getting what you exactly mean? Especially, by user going to any checkpoint i order. Can you give some example ?

**Comment by mliu59** [comment]
@imvbh My bad, I misread the filename you edited. The checkpoint list that @bricehalder was referring to was for the marathon list module on the home page, implemented in static/js/modules/game/marathon/marathonPrompts.js.

**Comment by dqian3** [comment]
Closing for inactivity.

**Pull request closed without merging**
