### PR TITLE
Generator page and lobbies generator page

### PR DESCRIPTION
**Pull request by dqian3**

### CODE REVIEW

**Comment by bricehalder** [comment]
I think this will be a good base to transition to personal leaderboards. i.e. replacing leaderboards with only your runs, but not necessarily on a separate page for now

**Review by bricehalder — CHANGES_REQUESTED** [review]
See comment above - basically just change the text. Also, maybe it should be expanded by default?

**Comment by mliu59** [comment]
Are there additional setup steps for local? I haven't been able to try it
- Agreed with all Brice has mentioned, especially "Obscurity" vs. "reachability"
- I still think we should increase the article pool size
- I think separate start/end should be the default, and the generator block should be a vue component/js module since we're gonna use it in multiple places

**Comment by dqian3** [comment]
image

**Comment by bricehalder** [comment]
Hmm, I think the numbers still make it confusing. e.g. what does 50 obscurity mean, or 3000 articles? It's not really obvious to a user I think. What about if we just had the sliding scale and had it look like:

More Common ----O------------- Less Common

or

Easy ---O------------- Hard

but I prefer the first one.

**Pull request merged**
