### PR TITLE
User play info

### PR DESCRIPTION
**Pull request by dqian3**
Moved play link into separate col, and use played data to display play again/view results

image

### CODE REVIEW

**Comment by dqian3** [comment]
Option 2:
image

**Comment by mliu59** [comment]
Option 2 seems cleaner, at least from the screenshot. How do these look on mobile?

**Comment by mliu59** [comment]
Suggest moving (play (again)) to the prompt # col
image

Will look better on mobile and also be consistent with where the link to play a prompt is

**Review by mliu59 — CHANGES_REQUESTED** [review]
See comment above

**Comment by dqian3** [comment]
image
image

**Pull request merged**
