### PR TITLE
Add discord bot daily message reports

### PR DESCRIPTION
**Pull request by mliu59**
Added a discord bot script to automate text reports. I built this to take in a configurable list of tasks outputting strings. 

The script currently uses system environment variables for target channel ids and the bot token. On windows:
>>$env:CHANNEL_ID = "..."
>> $env:BOT_TOKEN = "..."

Current daily tasks are:
- report number of new runs and users
- report number of consecutives days we still have prompts for

### CODE REVIEW

**Comment by dqian3** [comment]
Might be good as its own repo?

Also might be fun to some public reports, such as the best run for POTD, or announcements for when the POTD is released.

**Comment by bricehalder** [comment]
+1 this might be better as its own repo

**Comment by dqian3** [comment]
@mliu59 Do we still need this with https://github.com/wikispeedruns/wikispeedruns-discord-bot?

**Comment by mliu59** [comment]
> @mliu59 Do we still need this with https://github.com/wikispeedruns/wikispeedruns-discord-bot?

I think we're good to close this. Continuing on the separate repo

**Pull request closed without merging**
