### PR TITLE
Add QR Code for joining lobbies

### PR DESCRIPTION
**Pull request by RolandSmarzik**
1.Added library qrcode from npm into the project via command : npm install qrcode
2.Modified lobby html to contain a new dropdown button which generates a QR code (placement to where the other buttons were)
3.Modified lobby.js to contain global import of npm qrcode library which is then used in added asynch method generateQRCode which builds the qr code of current lobby and displays it upon dropdown click in lobby.
Images of generated QRCode :

Image of not clicked dropdown:
image

Image of clicked dropdown:
image

### CODE REVIEW

**Comment by Resonantjacket5** [comment]
Did a brief review, looks pretty good. The code to take it from the existing page looks pretty nice too as we can easily add the button to other pages as well. 

I'll ping brice to merge it. 

Other stuff:
Depending on how long it takes to calculate it might be nice just show the qr code when the page loads, especially for sharing it to other mobile users, but we can leave that for a future pr.

**Comment by RolandSmarzik** [comment]
One thing that i just remembered is that I commited the update package.lock and json but just remembered that your architecture has a requirements.txt in scripts, should i remove the package commit and add the required library into requirements.txt ?

**Comment by dqian3** [comment]
> One thing that i just remembered is that I commited the update package.lock and json but just remembered that your architecture has a requirements.txt in scripts, should i remove the package commit and add the required library into requirements.txt ?

That is for the backend python requirements, this should be fine.

**Comment by dqian3** [comment]
Just merged in main for you!

**Comment by RolandSmarzik** [comment]
Hi currently I have implemented the saving of the qr code in higher resolution, is the 3rd step still needed or is the 2nd step enough ?

**Comment by Resonantjacket5** [comment]
Hi Dan,

I think we should leave those tasks to a separate pr it’ll probably be too much to implement 4 new features. Especially creating a separate page will take some time to setup.

**Comment by dqian3** [comment]
Yeah, just having the higher resolution code and an easy way to save it should be fine! They can always get their own page! Once you have that in I can try it out again and it should be ready to merge.

**Comment by RolandSmarzik** [comment]
Hi, Could you please take a look at these screenshots if this matches your requirements of the first 2 points ? 
image
image
image
Best Regards,
Roland

**Comment by RolandSmarzik** [comment]
Regarding the colapsible permanent image instead of a dropdown, I solved it with an invocation of generateQRCode method in the mounted of lobby.js
This way the QR Code is preloaded on the page when the user opens the lobby.

**Comment by dqian3** [comment]
Looks great I will take care of the merge conflicts and myself and can merge it once done!

**Review by dqian3 — APPROVED** [review]

**Pull request merged**
