### PR TITLE
PR to address minor UI features

### PR DESCRIPTION
**Pull request by mliu59**
NOT mobile specific UI changes

### CODE REVIEW

**Comment by dqian3** [comment]
Small thing: the end of article marker (as well as the HUD) are displayed while loading. Probably want to turn that off by default

image

**Comment by mliu59** [comment]
conflicts resolved, verified on local

**Review by dqian3 — CHANGES_REQUESTED** [review]
The end of article maker and timebox still show up? 
Also the screen goes black before the prompt starts? 

Lmk if you need me to reproduce these.

**Comment by mliu59** [comment]
> The end of article maker and timebox still show up? Also the screen goes black before the prompt starts?
> 
> Lmk if you need me to reproduce these.

I can't seem to reproduce these myself, so yes pls

**Comment by dqian3** [comment]
Fixed it myself lol, merging

**Review by dqian3 — APPROVED** [review]

**Pull request merged**
